on:
  push:
  pull_request:

jobs:
  hacs-validate:
    name: HACS Validation
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - name: HACS validation
        uses: 'hacs/action@main'
        with:
          category: 'integration'
  hassfest-validate:
    name: hassfest Validation
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - uses: home-assistant/actions/hassfest@master
